# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Guilherme/Documents/UnB/Pratica de Eletronica Digital 2/2019_1/SAD/SAD.srcs/sources_1/ip/ROM2/ROM2.xci
# IP: The module: 'ROM2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Guilherme/Documents/UnB/Pratica de Eletronica Digital 2/2019_1/SAD/SAD.srcs/sources_1/ip/ROM2/ROM2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Guilherme/Documents/UnB/Pratica de Eletronica Digital 2/2019_1/SAD/SAD.srcs/sources_1/ip/ROM2/ROM2.xci
# IP: The module: 'ROM2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Guilherme/Documents/UnB/Pratica de Eletronica Digital 2/2019_1/SAD/SAD.srcs/sources_1/ip/ROM2/ROM2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
